# Generated by Django 4.2.23 on 2025-06-26 07:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=150)),
                ('street_nr', models.CharField(max_length=10)),
                ('street_box', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('mobile_nr_1', models.CharField(max_length=20)),
                ('mobile_nr_2', models.CharField(max_length=20)),
                ('fixed_nr_1', models.CharField(max_length=20)),
                ('email_1', models.EmailField(max_length=50)),
                ('email_2', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('permissions', models.ManyToManyField(related_name='permissions', to='membership.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('U', 'Inconnu')], default='U', max_length=10)),
                ('birthdate', models.DateField()),
                ('registration_start_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('registration_end_date', models.DateTimeField(null=True)),
                ('sponsored', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AC', 'Actif'), ('NA', 'Inactif'), ('SP', 'Suspendu'), ('PD', 'En attente'), ('IC', 'Inscription en cours'), ('RM', 'Radié')], default='NA', max_length=10)),
                ('function', models.CharField(max_length=100, null=True)),
                ('roles', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('H', "Membre d'honneur"), ('O', 'Membre ordinaire')], default='O', max_length=10)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('grade', models.CharField(choices=[('N', 'Aucun'), ('BV', 'Brevet'), ('HS', 'Baccalauréat'), ('BC', 'Bachelier'), ('GD', 'Graduat'), ('LC', 'Licence'), ('MA', 'Master'), ('PH', 'Doctorat'), ('EN', 'Ingénieur')], default='N', max_length=20)),
                ('marital_status', models.CharField(choices=[('S', 'Célibataire'), ('M', 'Marié(e)'), ('C', 'Cohabitant'), ('W', 'Veuf(ve)'), ('U', 'Inconnu')], default='U', max_length=10)),
                ('child_count', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='membership.branch')),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.contact')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.member')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('responsible', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.country')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.country'),
        ),
        migrations.AddField(
            model_name='branch',
            name='federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='membership.federation'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('federation', 'name'), name='unique_federation_branch'),
        ),
    ]
