# Generated by Django 4.2.23 on 2025-06-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.contact'),
        ),
    ]
