# Generated by Django 4.2.23 on 2025-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.CharField(choices=[('N', 'Aucun'), ('BV', 'Brevet'), ('HS', 'Baccalauréat'), ('BC', 'Bachelier'), ('GD', 'Graduat'), ('LC', 'Licence'), ('MA', 'Master'), ('PH', 'Doctorat'), ('EN', 'Ingénieur')], default='N', max_length=20),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
