# Generated by Django 5.2.2 on 2025-06-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_federation_permission_member_email_alter_member_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=150)),
                ('street_nr', models.CharField(max_length=10)),
                ('street_box', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('mobile_nr_1', models.CharField(max_length=20)),
                ('mobile_nr_2', models.CharField(max_length=20)),
                ('fixed_nr_1', models.CharField(max_length=20)),
                ('email_1', models.EmailField(max_length=50)),
                ('email_2', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='federation',
            name='code',
        ),
        migrations.AddField(
            model_name='member',
            name='registration_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('U', 'Inconnu')], default='U', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='federation',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='federation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='membership.federation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.branch'),
        ),
        migrations.AddField(
            model_name='member',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contact', to='membership.contact'),
        ),
        migrations.AddField(
            model_name='federation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.country'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.memberstatus'),
        ),
    ]
