# Generated by Django 4.2.23 on 2025-06-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_member_grade_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('H', "Membre d'honneur"), ('O', 'Membre ordinaire')], default='O', max_length=10),
        ),
    ]
