# Generated by Django 4.2.23 on 2025-06-24 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_member_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_start_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
