# Generated by Django 5.2.2 on 2025-06-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_contact_country_grade_memberstatus_membertitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('H', "Membre d'honneur"), ('O', 'Membre ordinaire'), ('U', 'Inconnu')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='function',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='membership.grade'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Célibataire'), ('M', 'Marié(e)'), ('C', 'Cohabitant'), ('W', 'Veuf(ve)'), ('U', 'Inconnu')], default='U', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
