# Generated by Django 5.2.2 on 2025-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_member_category_member_child_count_member_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federation',
            name='responsible',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
