# Generated by Django 5.2.2 on 2025-06-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_remove_persontype_id_alter_branch_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('federation', 'name'), name='unique_federation_branch'),
        ),
    ]
