# Generated by Django 4.2.23 on 2025-06-14 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_branch_unique_federation_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='federation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='membership.federation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='membership.branch'),
        ),
    ]
