# Generated by Django 4.2.23 on 2025-08-08 05:07

from django.utils import timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0015_alter_member_first_name_alter_member_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.TextField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('federation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='membership.federation')),
            ],
        ),
    ]
