# Generated by Django 4.2.23 on 2025-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
