# Generated by Django 5.2.2 on 2025-06-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0004_member_category_member_child_count_member_function_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=150)),
                ('current_price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(null=True)),
                ('sending_date', models.DateTimeField(null=True)),
                ('confirmation_date', models.DateTimeField(null=True)),
                ('cancelling_date', models.DateTimeField(null=True)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(null=True)),
                ('change_date', models.DateTimeField(null=True)),
                ('new_price', models.FloatField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('D', 'Réduction'), ('P', 'Pourcentage réduction'), ('F', 'Prix final')], default='P', max_length=20)),
                ('value', models.FloatField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='shop.productgroup'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('used_price', models.FloatField(null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'cart'), name='unique_order_line')],
            },
        ),
    ]
