# Generated by Django 5.2.2 on 2025-06-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='value',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='current_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='discount', to='shop.discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_final_price',
            field=models.FloatField(null=True),
        ),
    ]
