# Generated by Django 4.2.23 on 2025-06-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_discount_id_alter_pricechange_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StorageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.store')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.store')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('product', 'store'), name='unique_storage'),
        ),
    ]
